config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :acudientes
  resources :documentos
  resources :volantes
  resources :horarios
  resources :estudiantes
  resources :acudientes

  root 'home#index'

  get 'home/mision_vision' => 'home#mision_vision'
  get 'home/galeria' => 'home#galeria'
  get 'home/manual' => 'home#manual'
  get 'home/contactenos' => 'home#contactenos'

  patch 'admin/estudiantes/:id' => 'estudiantes#actualizar', as: :actualizar_estudiante
  get 'admin/estudiantes/:id/editar' => 'estudiantes#editar', as: :editar_estudiante
  

end

app/models/acudiente.rb
class Acudiente < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :estudiantes

	validates :identificacion, uniqueness:true
	
end

app/controllers/acudientes_controller.rb
class AcudientesController < ApplicationController
  before_action :set_acudiente, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception
  

  # GET /acudientes
  # GET /acudientes.json
  def index
    @acudientes = Acudiente.all
  end

  # GET /acudientes/1
  # GET /acudientes/1.json
  def show
  end

  # GET /acudientes/new
  def new
    @acudiente = Acudiente.new
  end

  # GET /acudientes/1/edit
  def edit
  end

  # POST /acudientes
  # POST /acudientes.json
  def create
    if Acudiente.find(params[:identificacion])?
    else
    @acudiente = Acudiente.new(acudiente_params)

    respond_to do |format|
      if @acudiente.save
        format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Acudiente creado exitosamente' }
        format.json { render :show, status: :created, location: @acudiente }
      else
        format.html { render :new, notice: 'ERROR'}
        format.json { render json: @acudiente.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # PATCH/PUT /acudientes/1
  # PATCH/PUT /acudientes/1.json
  def update
    respond_to do |format|
      if @acudiente.update(acudiente_params)
        format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Acudiente actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @acudiente }
      else
        format.html { render :edit }
        format.json { render json: @acudiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acudientes/1
  # DELETE /acudientes/1.json
  def destroy
    @acudiente.destroy
    respond_to do |format|
      format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Acudiente eliminado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acudiente
      @acudiente = Acudiente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acudiente_params
      params.require(:acudiente).permit(:nombre, :apellidos, :identificacion, :ocupacion, :cargo, :empresa, :direccion, :telefono, :celular)
    end

   
end

app/helpers/acudientes_helper.rb
module AcudientesHelper
end

app/views/acudientes/_form.html.erb
<%= form_for(@acudiente) do |f| %>
  <% if @acudiente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acudiente.errors.count, "error") %> prohibited this acudiente from being saved:</h2>

      <ul>
      <% @acudiente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :identificacion %><br>
    <%= f.text_field :identificacion %>
  </div>
  <div class="field">
    <%= f.label :ocupacion %><br>
    <%= f.text_field :ocupacion %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.text_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :empresa %><br>
    <%= f.text_field :empresa %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.number_field :celular %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acudientes/edit.html.erb
<h1>Editing Acudiente</h1>

<%= render 'form' %>

<%= link_to 'Show', @acudiente %> |
<%= link_to 'Back', acudientes_path %>

app/views/acudientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Acudientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Identificacion</th>
      <th>Ocupacion</th>
      <th>Cargo</th>
      <th>Empresa</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acudientes.each do |acudiente| %>
      <tr>
        <td><%= acudiente.nombre %></td>
        <td><%= acudiente.apellidos %></td>
        <td><%= acudiente.identificacion %></td>
        <td><%= acudiente.ocupacion %></td>
        <td><%= acudiente.cargo %></td>
        <td><%= acudiente.empresa %></td>
        <td><%= acudiente.direccion %></td>
        <td><%= acudiente.telefono %></td>
        <td><%= acudiente.celular %></td>
        <td><%= link_to 'Show', acudiente %></td>
        <td><%= link_to 'Edit', edit_acudiente_path(acudiente) %></td>
        <td><%= link_to 'Destroy', acudiente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acudiente', new_acudiente_path %>

app/views/acudientes/new.html.erb
<h1>New Acudiente</h1>

<%= render 'form' %>

<%= link_to 'Back', acudientes_path %>

app/views/acudientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @acudiente.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @acudiente.apellidos %>
</p>

<p>
  <strong>Identificacion:</strong>
  <%= @acudiente.identificacion %>
</p>

<p>
  <strong>Ocupacion:</strong>
  <%= @acudiente.ocupacion %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @acudiente.cargo %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @acudiente.empresa %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @acudiente.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @acudiente.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @acudiente.celular %>
</p>

<%= link_to 'Edit', edit_acudiente_path(@acudiente) %> |
<%= link_to 'Back', acudientes_path %>