config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :acudientes
  resources :documentos
  resources :volantes
  resources :horarios
  resources :estudiantes
  resources :acudientes

  root 'home#index'

  get 'home/mision_vision' => 'home#mision_vision'
  get 'home/galeria' => 'home#galeria'
  get 'home/manual' => 'home#manual'
  get 'home/contactenos' => 'home#contactenos'

  patch 'admin/estudiantes/:id' => 'estudiantes#actualizar', as: :actualizar_estudiante
  get 'admin/estudiantes/:id/editar' => 'estudiantes#editar', as: :editar_estudiante
  

end

app/models/volante.rb
class Volante < ActiveRecord::Base
	belongs_to :estudiante
	has_attached_file :soporte
    validates_attachment_content_type :soporte, :content_type => ['image/jpeg', 'image/png', 'application/pdf']
end

app/controllers/volantes_controller.rb
class VolantesController < ApplicationController
  before_action :set_volante, only: [:show, :edit, :update, :destroy]

  # GET /volantes
  # GET /volantes.json
  def index
    @volantes = Volante.all
  end

  # GET /volantes/1
  # GET /volantes/1.json
  def show
    request.format = "pdf"
    respond_to do |format|
      format.pdf do
        render pdf: "file_name",   # Excluding ".pdf" extension.
        layout: 'layouts/fpago.html.erb',  # layout used
        show_as_html: params[:debug].present?,
        target: "_blank"
      end
    end
  end

  # GET /volantes/new
  def new
    @volante = Volante.new
  end

  # GET /volantes/1/edit
  def edit
     
  end

  # POST /volantes
  # POST /volantes.json
  def create
    @volante = Volante.new(volante_params)
    
    @volante.f_generacion =Date.current.to_s

    @estudiante = Estudiante.find(@volante.estudiante_id)

    if @volante.concepto=="PAGO INSCRIPCION"
      @estudiante.update_attributes({
         :estado => "Pre Inscrito"
         
      });
    else
      @estudiante.update_attributes({
         :estado => "Matricula en Proceso"
         
      });
    end

    respond_to do |format|
      if @volante.save
        format.html { redirect_to @volante, notice: 'Volante creado exitosamente' }
        format.json { render :show, status: :created, location: @volante }
      else
        format.html { render :new }
        format.json { render json: @volante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volantes/1
  # PATCH/PUT /volantes/1.json
  def update
    @estudiante = Estudiante.find(@volante.estudiante.id)
      @volante.f_ingreso = Date.current.to_s
      

      @fecha = Horario.random
      @soporte = params[:soporte]

      fecha_hora = "#{@fecha.fecha} #{@fecha.hora_inicio} - #{@fecha.hora_fin}" 
      
      if @volante.concepto == "PAGO INSCRIPCION" && @volante.estudiante.estado == "Pre Inscrito"
      @estudiante.update_attributes({
         :estado => "Inscrito"
         
      });
      else
        if @volante.concepto == "PAGO MATRICULA" && @volante.estudiante.estado == "Matricula en Proceso"
          @estudiante.update_attributes({
             :estado => "Pendiente por firma",   
             :f_matricula  => fecha_hora
          });
        end
      end
    respond_to do |format|
      if @volante.update(volante_params)
        format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Volante actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @volante }
      else
        format.html { render :edit }
        format.json { render json: @volante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volantes/1
  # DELETE /volantes/1.json
  def destroy
    @volante.destroy
    respond_to do |format|
      format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Volante eliminado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volante
      @volante = Volante.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volante_params
      params.require(:volante).permit(:concepto, :valor, :f_generacion, :f_ingreso, :numero_comprobante, :estudiante_id, :id, :soporte)
    end

end

app/helpers/volantes_helper.rb
module VolantesHelper
end

app/views/volantes/_form.html.erb
<%= form_for @volante, :html => {:multipart => true} do |f| %>
  <% if @volante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volante.errors.count, "error") %> prohibited this volante from being saved:</h2>

      <ul>
      <% @volante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :concepto %><br>
    <%= f.text_field :concepto %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor %>
  </div>
  <div class="field">
    <%= f.label :f_generacion %><br>
    <%= f.date_select :f_generacion %>
  </div>
  <div class="field">
    <%= f.label :f_ingreso %><br>
    <%= f.date_select :f_ingreso %>
  </div>
  <div class="field">
    <%= f.label :numero_comprobante %><br>
    <%= f.text_field :numero_comprobante %>
  </div>
  <div class="field">
    <%= f.label :estudiante_id %><br>
    <%= f.number_field :estudiante_id %>
  </div>
  <div class="field">
            <%= f.label :soporte, "Adjunto" %>
            <%= f.file_field :soporte %>
        </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/volantes/edit.html.erb
<h1>Editing Volante</h1>

<%= render 'form' %>

<%= link_to 'Show', @volante %> |
<%= link_to 'Back', volantes_path %>

app/views/volantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Volantes</h1>

<table>
  <thead>
    <tr>
      <th>Concepto</th>
      <th>Valor</th>
      <th>F generacion</th>
      <th>F ingreso</th>
      <th>Numero comprobante</th>
      <th>Estudiante</th>
      <th>Soporte</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volantes.each do |volante| %>
      <tr>
        <td><%= volante.concepto %></td>
        <td><%= volante.valor %></td>
        <td><%= volante.f_generacion %></td>
        <td><%= volante.f_ingreso %></td>
        <td><%= volante.numero_comprobante %></td>
        <td><%= volante.estudiante_id %></td>
        <td><%= link_to volante.soporte.name, volante.soporte.url %></td>
        <td><%= link_to 'Show', volante %></td>
        <td><%= link_to 'Edit', edit_volante_path(volante) %></td>
        <td><%= link_to 'Destroy', volante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volante', new_volante_path %>

app/views/volantes/new.html.erb
<h1>New Volante</h1>

<%= render 'form' %>

<%= link_to 'Back', volantes_path %>

app/views/volantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concepto:</strong>
  <%= @volante.concepto %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @volante.valor %>
</p>

<p>
  <strong>F generacion:</strong>
  <%= @volante.f_generacion %>
</p>

<p>
  <strong>F ingreso:</strong>
  <%= @volante.f_ingreso %>
</p>

<p>
  <strong>Numero comprobante:</strong>
  <%= @volante.numero_comprobante %>
</p>

<p>
  <strong>Estudiante:</strong>
  <%= @volante.estudiante_id %>
</p>

<%= link_to 'Edit', edit_volante_path(@volante) %> |
<%= link_to 'Back', volantes_path %>

app/views/volantes/show.pdf.haml
<fieldset>

<TABLE BORDER=1 WIDTH=300 >

<legend>Datos Estudiante</legend>

<TR>
<TD WIDTH=100>
<p><strong>Nombre Estudiante:</strong></p> 
</TD> 

<TD WIDTH=100> 
<p><strong>Identificaci&oacuten:</strong></p>
</TD> 

<TD WIDTH=100> 
<p><strong>Codigo:</strong></p> 
</TD> 

<TD WIDTH=100> 
<p><strong>Fecha:</strong></p> 
</TD> 
</TR>

<TR>
<TD WIDTH=100>  

= "#{@volante.estudiante.nombre} #{@volante.estudiante.apellidos}"
</TD>

<TD WIDTH=100> 
= @volante.estudiante.doc_identidad
</TD> 

<TD WIDTH=100>
= @volante.id 
</TD>

<TD WIDTH=100> 
=@volante.f_generacion
</TD>
 
</TR>

</TABLE>

</fieldset>

<fieldset>
<TABLE BORDER=1 WIDTH=300>

<legend>Datos de Pago</legend>

<TR>
<TD WIDTH=100>
<p><strong>Banco:</strong></p>

</TD>

<TD WIDTH=100>
<p><strong>Direcci&oacuten:</strong></p>
</TD>

<TD WIDTH=100>
<p><strong>Cuenta:</strong></p>
</TD>

</TR>

<TR>
<TD WIDTH=100>

<p>BANCO AVVILLAS</p>

</TD>

<TD WIDTH=100>
<p>CUALQUIER SUCURSAL</p>
</TD>

<TD WIDTH=100>
<p>987654321987</p>
</TD>

</TR>

</TABLE>

</fieldset>


<fieldset>



<TABLE BORDER=1 WIDTH=300>



<TD WIDTH=100>
<p><strong>Concepto</strong></p>
</TD>

<TD WIDTH=100>
<p><strong>Valor</strong></p>
</TD>
</TR>

<TR>
<TD WIDTH=100>
=@volante.concepto
</TD>



<TD WIDTH=100>
=@volante.valor
</TD>

</TR>

<TR>


<TD WIDTH=100>
<p>Total</p>
</TD>

<TD WIDTH=100>
=@volante.valor
</TD>
</TR>

</TABLE>




</fieldset>


<br>
<br>
<br>

<hr>
<p align="center"> Firma Autorizada</p>

</form>