config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :acudientes
  resources :documentos
  resources :volantes
  resources :horarios
  resources :estudiantes
  resources :acudientes

  root 'home#index'

  get 'home/mision_vision' => 'home#mision_vision'
  get 'home/galeria' => 'home#galeria'
  get 'home/manual' => 'home#manual'
  get 'home/contactenos' => 'home#contactenos'

  patch 'admin/estudiantes/:id' => 'estudiantes#actualizar', as: :actualizar_estudiante
  get 'admin/estudiantes/:id/editar' => 'estudiantes#editar', as: :editar_estudiante
  

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
	belongs_to :acudiente
	has_many :documentos
	has_many :volantes
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_acudiente!

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end



  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)
    @estudiante.estado = "Aspirante"
    @estudiante.acudiente_id = current_acudiente.id

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Estudiante creado exitosamente' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Estudiante actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  def actualizar
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to "http://localhost:3000/admin/estudiantes", notice: 'Estudiante actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to "http://localhost:3000/estudiantes", notice: 'Estudiante eliminado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudiante_params
      params.require(:estudiante).permit(:nombre, :apellidos, :edad, :doc_identidad, :lugar_expedicion, :grado, :f_nacimiento, :institucion_anterior, :grado_aspirado, :estado, :acudiente_id, :f_examen, :f_matricula)
    end
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_form.html.erb
<div class="row text-center">
<h1>Datos del Estudiante</h1>
   <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 logo-wrapper">   

     <%= image_tag "ingresoe.png", :alt => "Resgistro Estudiante", :title => "Registro Estudiante"%>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 logo-wrapper">
  
<%= form_for @estudiante, :html => {:class => "form-horizontal"} do |f| %>
  

  <div class="form-group">
    <%= f.label :nombre, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.text_field :nombre, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :apellidos, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.text_field :apellidos, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :edad, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.number_field :edad, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :doc_identidad, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.text_field :doc_identidad, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lugar_expedicion, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.text_field :lugar_expedicion, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :grado, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.number_field :grado, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :f_nacimiento, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.date_select :f_nacimiento, start_year: 1995, last_year: 2010, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :institucion_anterior, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.text_field :institucion_anterior, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :grado_aspirado, class: "control-label col-xs-4" %>
    <div class="col-xs-8">
    <%= f.number_field :grado_aspirado, class: "form-control" %>
    </div>
  </div>
  <!--<div class="field">
    <%= f.label :estado %>
    <%= f.text_field :estado %>
  </div>-->
  <!--<div class="field">
    <%= f.label :acudiente_id %>
    <%= f.number_field :acudiente_id %>
  </div>-->
  <!--<div class="field">
    <%= f.label :f_examen %>
    <%= f.date_select :f_examen %>
  </div>
  <div class="field">
    <%= f.label :f_matricula %>
    <%= f.date_select :f_matricula %>
  </div>-->
  <div class="col-xs-offset-3 col-xs-9">
    <%= f.submit "Registrar", class: "btn btn-primary" %>
    <input type="reset" class="btn btn-default" value="Limpiar">
  </div>
<% end %>
</div>

<div class="col-lg-1 col-md-6 col-sm-6 col-xs-12 logo-wrapper">   

     
  </div>

</div>

app/views/estudiantes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estudiante.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @estudiante.apellidos %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @estudiante.edad %>
</p>

<p>
  <strong>Doc identidad:</strong>
  <%= @estudiante.doc_identidad %>
</p>

<p>
  <strong>Lugar expedicion:</strong>
  <%= @estudiante.lugar_expedicion %>
</p>

<p>
  <strong>Grado:</strong>
  <%= @estudiante.grado %>
</p>

<p>
  <strong>F nacimiento:</strong>
  <%= @estudiante.f_nacimiento %>
</p>

<p>
  <strong>Institucion anterior:</strong>
  <%= @estudiante.institucion_anterior %>
</p>

<p>
  <strong>Grado aspirado:</strong>
  <%= @estudiante.grado_aspirado %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @estudiante.estado %>
</p>

<p>
  <strong>Acudiente:</strong>
  <%= @estudiante.acudiente_id %>
</p>

<p>
  <strong>F examen:</strong>
  <%= @estudiante.f_examen %>
</p>

<p>
  <strong>F matricula:</strong>
  <%= @estudiante.f_matricula %>
</p>

<% @volante = Volante.new %>
<% $id_estudiante = @estudiante.id %>
<% @lista_volante = Volante.all %>


<% if @estudiante.estado == "Aspirante" %>
<%= form_for(@volante) do |f| %>
  <% if @volante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volante.errors.count, "error") %> prohibited this volante from being saved:</h2>

      <ul>
      <% @volante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

    <div class="field">
      <%= f.hidden_field :concepto, value: "PAGO INSCRIPCION"%>
    </div>
    <div class="field">
      <%= f.hidden_field :valor, value: "10000"%>
    </div>
    <div class="actions">
      <%= f.submit :Inscripcion%>
    </div> 
<% end %>

<% else %>
   <% @lista_volante.each do |volante| %>
      <% if @estudiante.id == volante.estudiante.id && volante.estudiante.estado =="Pre Inscrito"%>
        <% @volante = Volante.find(volante.id) %>
        <%= form_for @volante, url: volante_path(volante.id), :html => {:multipart => true} do |f| %>
          <% if @volante.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@volante.errors.count, "error") %> prohibited this volante from being saved:</h2>

              <ul>
              <% @volante.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %> 

         <div class="field">
              <%= f.hidden_field :id, value: volante.id%>
          </div>
          <div class="field">
            <%= f.label :numero_comprobante %><br>
            <%= f.text_field :numero_comprobante %>
          </div>
          <div class="field">
              <%= f.label :soporte, "Adjunto" %>
              <%= f.file_field :soporte %>
          </div>
          <div class="actions">
            <%= f.submit :Aceptar%>
          </div>     
        <% end %>        
      <% end %>
   <% end %>   
  <% end %>

<% if @estudiante.estado == "Aprobado" %>
  <%= form_for(@volante) do |f| %>
    <% if @volante.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@volante.errors.count, "error") %> prohibited this volante from being saved:</h2>

        <ul>
        <% @volante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :concepto, value: "PAGO MATRICULA"%>
    </div>
    <div class="field">
      <%= f.hidden_field :valor, value: "180000"%>
    </div>
    <div class="actions">
      <%= f.submit :Matricula%>
    </div>
  <% end %>
<% end %>

 




<%= link_to 'Edit', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Add New', new_estudiante_path %>
<%= link_to 'End', :controller => "home" %>